version: '3.8'

services:
  gym-nfc-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET_KEY=your-super-secret-jwt-key-change-this-in-production
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - APP_NAME=Gym NFC Management System
      - APP_VERSION=1.0.0
      - DEBUG=false
      - NFC_READER_TIMEOUT=30
      - NFC_WRITE_TIMEOUT=10
    devices:
      # Mount USB devices for NFC reader access
      - /dev/bus/usb:/dev/bus/usb
    privileged: true  # Required for USB device access
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

# Note: For NFC functionality in Docker, you may need to:
# 1. Install appropriate drivers on the host system
# 2. Ensure the container has access to USB devices
# 3. Run with appropriate privileges
# 4. Consider running the NFC service on the host instead